version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0
    steps:
      - checkout
      - run: mvn clean install

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build