version: 2.1

orbs:
  maven: circleci/maven@1.0.1

jobs:
  build_and_test:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
            - maven-repo-v1-{{ .Branch }}
            - maven-repo-v1-
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: maven-repo-v1-{{ .Branch }}-{{ checksum "pom.xml" }}
      - run: mvn clean package
      - run: mvn test
